permissions:
    log-players: false
    backends:
        file:
            file: permissions.yml
    backend: file
    superperms:
        parent-nodes: true
        enable: true
        strict-mode: false
    createUserRecords: false
    allowOps: false
    debug: false
    basedir: plugins\PermissionsEx
